### ISSUE TITLE
Renk Aralıkları

### ISSUE THREAD

**Issue by MuhammetDilmac** [isagul/covid-turkey-risk-map#1]
Selamlar,
Renk aralıkları README'de farklı yazıyor kod'da farklı yazıyor. Hangisi gerçek? Haber sitelerinden de emin olamadım gerçekten bilen birisi yazarsa ikisinden birisini düzenleyelim :)

**Comment by isagul** [comment]
Selamlar :)
Aslında doğru olan koddaki. Şuradaki [linkte](https://www.bbc.com/turkce/haberler-turkiye-56127235) bu şekilde belirtiliyor. Hatta projedeki drawer'da da doğru ama README'yi güncellemeyi unutmuşum :( :(

**Comment by MuhammetDilmac** [comment]
Kodda ki doğru ise süper :) Ben sarı'dan devam yakında her yerin mavi olması dilekleri ile :)
